### PR TITLE
added the Long built in type

### PR DESCRIPTION
**Pull request by creactiviti**
Added a built-in Long scalar type.

### CODE REVIEW

**Comment by andimarek** [comment]
Thanks for taking your time and creating this PR, but there is an Issues with this approach:

We can't just add a new language element like LongValue. We want to conform to the spec and there is simply no literal for representing long values. The official way for new scalar types is to represent them as Strings.

This is done in the `coerceLiteral` method: Converting String to Long. So I would suggest I will add something like the code snippet I pasted here: https://github.com/andimarek/graphql-java/issues/6

I hope this is ok for you and will fit your needs.

**Comment by creactiviti** [comment]
Cool @andimarek. I think that's very workable. Thanks.

**Comment by andimarek** [comment]
I added the type in this commit: https://github.com/andimarek/graphql-java/commit/948231fb92ea39c47ed639ba8ce44c8e8ea82412

**Comment by creactiviti** [comment]
Thanks @andimarek

**Pull request closed without merging**
