### PR TITLE
Recursively adding input types

### PR DESCRIPTION
**Pull request by cardinalraven**

### CODE REVIEW

**Comment by cardinalraven** [comment]
Oh, editor dropped some crap we don't want, will resubmit

**Comment by andimarek** [comment]
Thanks for this PR!

Do I understand this correct that this is BugFix and currently input types are not collected when they are not top level input types in the Schema?

**Comment by cardinalraven** [comment]
Your understanding is correct.  The unit test I included in SchemaUtilTest will fail if you undo my change to SchemaUtil (it won't get the Range type).

**Comment by andimarek** [comment]
Thanks .... I merge it.

**Pull request merged**
