### PR TITLE
Feature/batching

### PR DESCRIPTION
**Pull request by cardinalraven**
Pull request for BatchedExecutionStrategy.

This allows for explicit batching of data fetching operations.

See the tests for examples of use.

### CODE REVIEW

**Comment by andimarek** [comment]
Thanks a lot for this PR!

I will get back to you, when I looked at it in detail.

**Comment by andimarek** [comment]
Thanks again for this amazing PR. 

One formal thing about the tests: We are using [Spock](http://spockframework.github.io/spock/docs/1.0/index.html) as the test framework. Is it possible for you to rewrite the tests using Spock?

**Comment by cardinalraven** [comment]
Yes, I'm using this code in a production environment, plus a corresponding production-like test environment.  No issues reported thus far.  Only difference is that I backported the code to Java 7 and removed the Guava specifically to include in graphql-java.  

I can take a crack at Spock.  Might be a little while.  I'll let you know if I hit issues -- for my previous PR I was able to fake knowledge of Spock by copying-and-pasting.

**Comment by andimarek** [comment]
Thanks @cardinalraven for your awesome work. I merged your PR into master. Especially for also writing docs and changing the tests into spock. 

Thanks!

**Comment by cardinalraven** [comment]
Sweet!

**Comment by andimarek** [comment]
Just a tip: You might wanna configure your email address ... see screenshot:
screen shot 2016-01-18 at 19 08 30

**Comment by cardinalraven** [comment]
Thanks, I just added dcohen@palantir.com to github.  Do you still get that
"unrecognized author"?

**Comment by andimarek** [comment]
Now its fine :-)

**Pull request closed without merging**
